name: Build & Test

on:
  push:
    branches: [ wizards ]
  pull_request:
    branches: [ wizards ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Wizards
      uses: actions/checkout@v2

    - name: Setup .NET 7.0.X
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Debug --no-restore

    # test requires libfluidsynth.so for v2.0 installed, which is not on ubuntu-latest
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
